services:
  - docker

deploy:
  provider: script
  script: bash scripts/deploy.sh production
  on:
    branch: master
deploy:
  provider: script
  script: bash scripts/deploy.sh latest
  on:
    branch: development
