name: Push Docker Image (development)

on:
  push:
    branches:
    - development

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
        ref: development
    - name: docker build
      run: docker build . --tag shroomlife/oerwi:development
    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: docker push
      run: docker push shroomlife/oerwi:development
