name: Push Docker Image (main)

on:
  push:
    branches:
    - main

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@main
      with:
        ref: main
    - name: docker build
      run: docker build . --tag shroomlife/oerwi:latest
    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: docker push
      run: docker push shroomlife/oerwi:latest
