name: Push Docker Image (master)

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: docker build
      run: docker build . --tag shroomlife/oerwi:master
    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: docker push
      run: docker push shroomlife/oerwi:master
